#配置token生成策略
config:
  jwt:
    secret: test1@Login(Auth}*^31)&heiMa% #这里可以自己定制
    expire: 30 # 过期时间,单位分钟
    header: testProject #随意定制
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: myredispassword
    jedis:
      pool:
        max-idle: 16
        min-idle: 0
        max-wait: -1ms
    timeout: 10000